//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezerVanaUmv.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To d or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RezerVanaUmv.Resources.Resource - Copy", typeof(Resource___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÇIKLAMA.
        /// </summary>
        public static string AÇIKLAMA {
            get {
                return ResourceManager.GetString("AÇIKLAMA", resourceCulture);
            }
        }

        public static string İletişim
        {
            get
            {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        public static string Giriş_Yap
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        public static string AllStations
        {
            get
            {
                return ResourceManager.GetString("All Stations", resourceCulture);
            }
        }
        public static string dmguaReport
        {
            get
            {
                return ResourceManager.GetString("Damage Assessment Report", resourceCulture);
            }
        }
        public static string BagPcs
        {
            get
            {
                return ResourceManager.GetString("Bags Pcs", resourceCulture);
            }
        }

        public static string Acele_Mesaj_Sırası
        {
            get
            {
                return ResourceManager.GetString("Fwd No", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string Açıklama {
            get {
                return ResourceManager.GetString("Açıklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÇIKLAMALAR.
        /// </summary>
        public static string AÇIKLAMALAR {
            get {
                return ResourceManager.GetString("AÇIKLAMALAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADI-1.
        /// </summary>
        public static string ADI_1 {
            get {
                return ResourceManager.GetString("ADI-1", resourceCulture);
            }
        }

        public static string Uçak_Altı
        {
            get
            {
                return ResourceManager.GetString("Under Aircraft", resourceCulture);
            }
        }
        public static string Dosya_Seciniz
        {
            get
            {
                return ResourceManager.GetString("Choose a File", resourceCulture);
            }
        }
        public static string Ucak_Alti_Yukleme {
            get {
                return ResourceManager.GetString("Under Aircraft Loading", resourceCulture);
            }
        }
        public static string Ucak_Alti_Bosaltma {
            get {
                return ResourceManager.GetString("Under Aircraft Unloading", resourceCulture);
            }
        }
        public static string Sut_Alti_Yukleme {
            get {
                return ResourceManager.GetString("Chute Area Loading", resourceCulture);
            }
        }
       public static string Sut_Alti_Bosaltma {
            get {
                return ResourceManager.GetString("Chute Area Unloading", resourceCulture);
            }
        }

		public static string Bant
		{
			get
			{
				return ResourceManager.GetString("Band", resourceCulture);
			}
		}
		/// <summary>
		///   Looks up a localized string similar to ADI-2.
		/// </summary>
		public static string ADI_2 {
            get {
                return ResourceManager.GetString("ADI-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bagaj.
        /// </summary>
        public static string Bagaj {
            get {
                return ResourceManager.GetString("Bagaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAGAJIN BİLGİLERİ.
        /// </summary>
        public static string BAGAJIN_BİLGİLERİ {
            get {
                return ResourceManager.GetString("BAGAJIN BİLGİLERİ", resourceCulture);
            }
        }

		public static string Sutaltı
		{
			get
			{
				return ResourceManager.GetString("Şutaltı", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to BAGAJIN ROTASI.
		/// </summary>
		public static string BAGAJIN_ROTASI {
            get {
                return ResourceManager.GetString("BAGAJIN ROTASI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BH-1.
        /// </summary>
        public static string BH_1 {
            get {
                return ResourceManager.GetString("BH-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BH-2.
        /// </summary>
        public static string BH_2 {
            get {
                return ResourceManager.GetString("BH-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOŞ.
        /// </summary>
        public static string BOŞ {
            get {
                return ResourceManager.GetString("BOŞ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÖNÜŞ SAATİ.
        /// </summary>
        public static string DÖNÜŞ_SAATİ {
            get {
                return ResourceManager.GetString("DÖNÜŞ SAATİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÖNÜŞ TARİHİ.
        /// </summary>
        public static string DÖNÜŞ_TARİHİ {
            get {
                return ResourceManager.GetString("DÖNÜŞ TARİHİ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string E_Posta {
            get {
                return ResourceManager.GetString("E-Posta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string Ekle {
            get {
                return ResourceManager.GetString("Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksik Bagaj Bilgileri.
        /// </summary>
        public static string EksikBagajBilgileri {
            get {
                return ResourceManager.GetString("EksikBagajBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkek.
        /// </summary>
        public static string Erkek {
            get {
                return ResourceManager.GetString("Erkek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket No.
        /// </summary>
        public static string Etiket_No {
            get {
                return ResourceManager.GetString("Etiket No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ev/İş Telefonu.
        /// </summary>
        public static string Ev_İş_Telefonu {
            get {
                return ResourceManager.GetString("Ev/İş Telefonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEÇİCİ ADRESİ.
        /// </summary>
        public static string GEÇİCİ_ADRESİ {
            get {
                return ResourceManager.GetString("GEÇİCİ ADRESİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Bagaj Bilgileri.
        /// </summary>
        public static string GenelBagajBilgileri {
            get {
                return ResourceManager.GetString("GenelBagajBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hava Yolu.
        /// </summary>
        public static string Hava_Yolu {
            get {
                return ResourceManager.GetString("Hava Yolu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havayolu:.
        /// </summary>
        public static string Havayolu_ {
            get {
                return ResourceManager.GetString("Havayolu:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik Açıklama-1.
        /// </summary>
        public static string İçerik_Açıklama_1 {
            get {
                return ResourceManager.GetString("İçerik Açıklama-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik Açıklama-2.
        /// </summary>
        public static string İçerik_Açıklama_2 {
            get {
                return ResourceManager.GetString("İçerik Açıklama-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik Açıklama-3.
        /// </summary>
        public static string İçerik_Açıklama_3 {
            get {
                return ResourceManager.GetString("İçerik Açıklama-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik Kategori-1.
        /// </summary>
        public static string İçerik_Kategori_1 {
            get {
                return ResourceManager.GetString("İçerik Kategori-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik Kategori-2.
        /// </summary>
        public static string İçerik_Kategori_2 {
            get {
                return ResourceManager.GetString("İçerik Kategori-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik Kategori-3.
        /// </summary>
        public static string İçerik_Kategori_3 {
            get {
                return ResourceManager.GetString("İçerik Kategori-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İKAMET ADRESİ.
        /// </summary>
        public static string İKAMET_ADRESİ {
            get {
                return ResourceManager.GetString("İKAMET ADRESİ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadın.
        /// </summary>
        public static string Kadın {
            get {
                return ResourceManager.GetString("Kadın", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka.
        /// </summary>
        public static string Marka {
            get {
                return ResourceManager.GetString("Marka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil/Cep Telefonu.
        /// </summary>
        public static string Mobil_Cep_Telefonu {
            get {
                return ResourceManager.GetString("Mobil/Cep Telefonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nereden.
        /// </summary>
        public static string Nereden {
            get {
                return ResourceManager.GetString("Nereden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nereye.
        /// </summary>
        public static string Nereye {
            get {
                return ResourceManager.GetString("Nereye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önce İstasyon Seçiniz.
        /// </summary>
        public static string Önce_İstasyon_Seçiniz {
            get {
                return ResourceManager.GetString("Önce İstasyon Seçiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özellik.
        /// </summary>
        public static string Özellik {
            get {
                return ResourceManager.GetString("Özellik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parça Sayısı.
        /// </summary>
        public static string ParçaSayısı {
            get {
                return ResourceManager.GetString("ParçaSayısı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renk.
        /// </summary>
        public static string Renk {
            get {
                return ResourceManager.GetString("Renk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Seçiniz.
        /// </summary>
        public static string Resim_Seçiniz {
            get {
                return ResourceManager.GetString("Resim Seçiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resmi Sil.
        /// </summary>
        public static string Resmi_Sil {
            get {
                return ResourceManager.GetString("Resmi Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sefer Sayısı.
        /// </summary>
        public static string Sefer_Sayısı {
            get {
                return ResourceManager.GetString("Sefer Sayısı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOYADI-1.
        /// </summary>
        public static string SOYADI_1 {
            get {
                return ResourceManager.GetString("SOYADI-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOYADI-2.
        /// </summary>
        public static string SOYADI_2 {
            get {
                return ResourceManager.GetString("SOYADI-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T KOD.
        /// </summary>
        public static string T_KOD {
            get {
                return ResourceManager.GetString("T KOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslim Edilen Bagaj Bilgileri.
        /// </summary>
        public static string TeslimEdilenBagajBilgileri {
            get {
                return ResourceManager.GetString("TeslimEdilenBagajBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Ağırlığı.
        /// </summary>
        public static string ToplamAğırlığı {
            get {
                return ResourceManager.GetString("ToplamAğırlığı", resourceCulture);
            }
        }

        public static string Planlama
        {
            get
            {
                return ResourceManager.GetString("Planning", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to TR.
        /// </summary>
        public static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yolcu.
        /// </summary>
        public static string Yolcu {
            get {
                return ResourceManager.GetString("Yolcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yolcunun BagsFollow Hesap Numarası.
        /// </summary>
        public static string Yolcunun_BagsFollow_Hesap_Numarası {
            get {
                return ResourceManager.GetString("Yolcunun BagsFollow Hesap Numarası", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOLCUNUN ROTASI.
        /// </summary>
        public static string YOLCUNUN_ROTASI {
            get {
                return ResourceManager.GetString("YOLCUNUN ROTASI", resourceCulture);
            }
        }
    }
}
